[ipc]
disable = true

[mining]
force_sealing = true
min_gas_price = 1
reseal_min_period = 0
reseal_on_txs = "none"

[misc]
log_file = "diamond-node.log"
logging = "txqueue=info,consensus=info,engine=info"

[network]
interface = "all"
nat = "none"
port = 17771
reserved_peers = "reserved-peers"

[parity]
base_path = "data"
chain = "spec.json"

[rpc]
disable = true

[secretstore]
disable = true

[websockets]
disable = true

